#!/bin/sh
set -eu
cargo clippy "$@" -- \
    -D warnings \
    -W clippy::pedantic \
    -W clippy::nursery \
    -W clippy::unwrap_used \
    -W clippy::expect_used \
    -A clippy::missing-const-for-fn \
    -A clippy::option-if-let-else \
    -W clippy::panic \
    -W clippy::todo
