#!/bin/sh
set -eu
ARGS="--package hangman_solver --bin hangman_solver $@ "
if echo -n "${ARGS}" | grep -vsG -- '-- ' - > /dev/null ; then
    ARGS="${ARGS} -- "
fi
# python3 -c "print(__import__('sys').argv[1:])" ${ARGS}
cargo clippy ${ARGS} \
    -W clippy::pedantic \
    -W clippy::nursery \
    -W clippy::unwrap_used \
    -W clippy::expect_used \
    -A clippy::missing-const-for-fn \
    -A clippy::option-if-let-else \
    -W clippy::panic \
    -W clippy::todo
