#!/bin/sh
set -eu
ARGS="$@"
cargo clippy  ${ARGS:-} -- \
    -D warnings \
    -W clippy::pedantic \
    -W clippy::nursery \
    -W clippy::unwrap_used \
    -W clippy::expect_used \
    -A clippy::missing-const-for-fn \
    -A clippy::option-if-let-else
