name: Deploy
on:
  push:
    branches: [main]
jobs:
  github-pages:
    name: GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Update rust
        run: rustup update stable && rustup default stable
      - name: Install wasm-pack
        run: cargo install wasm-pack
      - name: Build wasm
        run: wasm-pack build --target web --no-default-features --features=wasm-bindgen
      - name: Copy HTML
        run: cp web/index.html pkg/
      - name: Copy run.js
        run: sed 's|"../pkg/hangman_solver_lib.js"|"https://github.asozial.org/hangman_solver/hangman_solver_lib.js"|' web/run.js > pkg/run.js
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: pkg
      - name: Deploy GitHub Pages site
        id: deployment
        uses: actions/deploy-pages@v4
